language: php
php:
- '5.5'
- '5.4'

install:
   - composer install --dev

script:
  - ./vendor/bin/phpcs --standard=PSR2 src/ tests/
  - ./vendor/bin/phpunit --bootstrap ./tests/bootstrap.php tests/

notifications:
  slack: tatu:ifWJMnOS9BlzH3pxQfJryUUz

